/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DiagnosticRouteImport } from './routes/diagnostic'
import { Route as BenchmarkRouteImport } from './routes/benchmark'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalSetupRouteImport } from './routes/portal.setup'
import { Route as PortalCoachRouteImport } from './routes/portal.coach'
import { Route as ApiPublicQuizLeadRouteImport } from './routes/api/public/quiz-lead'
import { Route as ApiPublicDiagnosticTokenRouteImport } from './routes/api/public/diagnostic-token'
import { Route as ApiPublicDiagnosticResultRouteImport } from './routes/api/public/diagnostic-result'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticRoute = DiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarkRoute = BenchmarkRouteImport.update({
  id: '/benchmark',
  path: '/benchmark',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSetupRoute = PortalSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCoachRoute = PortalCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => PortalRoute,
} as any)
const ApiPublicQuizLeadRoute = ApiPublicQuizLeadRouteImport.update({
  id: '/api/public/quiz-lead',
  path: '/api/public/quiz-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiagnosticTokenRoute =
  ApiPublicDiagnosticTokenRouteImport.update({
    id: '/api/public/diagnostic-token',
    path: '/api/public/diagnostic-token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDiagnosticResultRoute =
  ApiPublicDiagnosticResultRouteImport.update({
    id: '/api/public/diagnostic-result',
    path: '/api/public/diagnostic-result',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/benchmark': typeof BenchmarkRoute
  '/diagnostic': typeof DiagnosticRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/portal/coach': typeof PortalCoachRoute
  '/portal/setup': typeof PortalSetupRoute
  '/portal/': typeof PortalIndexRoute
  '/api/public/diagnostic-result': typeof ApiPublicDiagnosticResultRoute
  '/api/public/diagnostic-token': typeof ApiPublicDiagnosticTokenRoute
  '/api/public/quiz-lead': typeof ApiPublicQuizLeadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/benchmark': typeof BenchmarkRoute
  '/diagnostic': typeof DiagnosticRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/portal/coach': typeof PortalCoachRoute
  '/portal/setup': typeof PortalSetupRoute
  '/portal': typeof PortalIndexRoute
  '/api/public/diagnostic-result': typeof ApiPublicDiagnosticResultRoute
  '/api/public/diagnostic-token': typeof ApiPublicDiagnosticTokenRoute
  '/api/public/quiz-lead': typeof ApiPublicQuizLeadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/benchmark': typeof BenchmarkRoute
  '/diagnostic': typeof DiagnosticRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/portal/coach': typeof PortalCoachRoute
  '/portal/setup': typeof PortalSetupRoute
  '/portal/': typeof PortalIndexRoute
  '/api/public/diagnostic-result': typeof ApiPublicDiagnosticResultRoute
  '/api/public/diagnostic-token': typeof ApiPublicDiagnosticTokenRoute
  '/api/public/quiz-lead': typeof ApiPublicQuizLeadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/benchmark'
    | '/diagnostic'
    | '/login'
    | '/portal'
    | '/pricing'
    | '/signup'
    | '/portal/coach'
    | '/portal/setup'
    | '/portal/'
    | '/api/public/diagnostic-result'
    | '/api/public/diagnostic-token'
    | '/api/public/quiz-lead'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/benchmark'
    | '/diagnostic'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/portal/coach'
    | '/portal/setup'
    | '/portal'
    | '/api/public/diagnostic-result'
    | '/api/public/diagnostic-token'
    | '/api/public/quiz-lead'
  id:
    | '__root__'
    | '/'
    | '/benchmark'
    | '/diagnostic'
    | '/login'
    | '/portal'
    | '/pricing'
    | '/signup'
    | '/portal/coach'
    | '/portal/setup'
    | '/portal/'
    | '/api/public/diagnostic-result'
    | '/api/public/diagnostic-token'
    | '/api/public/quiz-lead'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenchmarkRoute: typeof BenchmarkRoute
  DiagnosticRoute: typeof DiagnosticRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  ApiPublicDiagnosticResultRoute: typeof ApiPublicDiagnosticResultRoute
  ApiPublicDiagnosticTokenRoute: typeof ApiPublicDiagnosticTokenRoute
  ApiPublicQuizLeadRoute: typeof ApiPublicQuizLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic': {
      id: '/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof DiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmark': {
      id: '/benchmark'
      path: '/benchmark'
      fullPath: '/benchmark'
      preLoaderRoute: typeof BenchmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/setup': {
      id: '/portal/setup'
      path: '/setup'
      fullPath: '/portal/setup'
      preLoaderRoute: typeof PortalSetupRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/coach': {
      id: '/portal/coach'
      path: '/coach'
      fullPath: '/portal/coach'
      preLoaderRoute: typeof PortalCoachRouteImport
      parentRoute: typeof PortalRoute
    }
    '/api/public/quiz-lead': {
      id: '/api/public/quiz-lead'
      path: '/api/public/quiz-lead'
      fullPath: '/api/public/quiz-lead'
      preLoaderRoute: typeof ApiPublicQuizLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/diagnostic-token': {
      id: '/api/public/diagnostic-token'
      path: '/api/public/diagnostic-token'
      fullPath: '/api/public/diagnostic-token'
      preLoaderRoute: typeof ApiPublicDiagnosticTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/diagnostic-result': {
      id: '/api/public/diagnostic-result'
      path: '/api/public/diagnostic-result'
      fullPath: '/api/public/diagnostic-result'
      preLoaderRoute: typeof ApiPublicDiagnosticResultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PortalRouteChildren {
  PortalCoachRoute: typeof PortalCoachRoute
  PortalSetupRoute: typeof PortalSetupRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalCoachRoute: PortalCoachRoute,
  PortalSetupRoute: PortalSetupRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenchmarkRoute: BenchmarkRoute,
  DiagnosticRoute: DiagnosticRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  ApiPublicDiagnosticResultRoute: ApiPublicDiagnosticResultRoute,
  ApiPublicDiagnosticTokenRoute: ApiPublicDiagnosticTokenRoute,
  ApiPublicQuizLeadRoute: ApiPublicQuizLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
