/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DiagnosticRouteImport } from './routes/diagnostic'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalSetupRouteImport } from './routes/portal.setup'
import { Route as PortalCoachRouteImport } from './routes/portal.coach'
import { Route as DiagnosticResultRouteImport } from './routes/diagnostic.result'
import { Route as ApiPublicQuizLeadRouteImport } from './routes/api/public/quiz-lead'
import { Route as ApiPublicDiagnosticTokenRouteImport } from './routes/api/public/diagnostic-token'
import { Route as ApiPublicDiagnosticResultRouteImport } from './routes/api/public/diagnostic-result'
import { Route as ApiPublicDiagnosticEmailRouteImport } from './routes/api/public/diagnostic-email'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticRoute = DiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSetupRoute = PortalSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCoachRoute = PortalCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => PortalRoute,
} as any)
const DiagnosticResultRoute = DiagnosticResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => DiagnosticRoute,
} as any)
const ApiPublicQuizLeadRoute = ApiPublicQuizLeadRouteImport.update({
  id: '/api/public/quiz-lead',
  path: '/api/public/quiz-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiagnosticTokenRoute =
  ApiPublicDiagnosticTokenRouteImport.update({
    id: '/api/public/diagnostic-token',
    path: '/api/public/diagnostic-token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDiagnosticResultRoute =
  ApiPublicDiagnosticResultRouteImport.update({
    id: '/api/public/diagnostic-result',
    path: '/api/public/diagnostic-result',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDiagnosticEmailRoute =
  ApiPublicDiagnosticEmailRouteImport.update({
    id: '/api/public/diagnostic-email',
    path: '/api/public/diagnostic-email',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostic': typeof DiagnosticRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/diagnostic/result': typeof DiagnosticResultRoute
  '/portal/coach': typeof PortalCoachRoute
  '/portal/setup': typeof PortalSetupRoute
  '/portal/': typeof PortalIndexRoute
  '/api/public/diagnostic-email': typeof ApiPublicDiagnosticEmailRoute
  '/api/public/diagnostic-result': typeof ApiPublicDiagnosticResultRoute
  '/api/public/diagnostic-token': typeof ApiPublicDiagnosticTokenRoute
  '/api/public/quiz-lead': typeof ApiPublicQuizLeadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostic': typeof DiagnosticRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/diagnostic/result': typeof DiagnosticResultRoute
  '/portal/coach': typeof PortalCoachRoute
  '/portal/setup': typeof PortalSetupRoute
  '/portal': typeof PortalIndexRoute
  '/api/public/diagnostic-email': typeof ApiPublicDiagnosticEmailRoute
  '/api/public/diagnostic-result': typeof ApiPublicDiagnosticResultRoute
  '/api/public/diagnostic-token': typeof ApiPublicDiagnosticTokenRoute
  '/api/public/quiz-lead': typeof ApiPublicQuizLeadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostic': typeof DiagnosticRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/diagnostic/result': typeof DiagnosticResultRoute
  '/portal/coach': typeof PortalCoachRoute
  '/portal/setup': typeof PortalSetupRoute
  '/portal/': typeof PortalIndexRoute
  '/api/public/diagnostic-email': typeof ApiPublicDiagnosticEmailRoute
  '/api/public/diagnostic-result': typeof ApiPublicDiagnosticResultRoute
  '/api/public/diagnostic-token': typeof ApiPublicDiagnosticTokenRoute
  '/api/public/quiz-lead': typeof ApiPublicQuizLeadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/diagnostic'
    | '/login'
    | '/portal'
    | '/pricing'
    | '/signup'
    | '/diagnostic/result'
    | '/portal/coach'
    | '/portal/setup'
    | '/portal/'
    | '/api/public/diagnostic-email'
    | '/api/public/diagnostic-result'
    | '/api/public/diagnostic-token'
    | '/api/public/quiz-lead'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/diagnostic'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/diagnostic/result'
    | '/portal/coach'
    | '/portal/setup'
    | '/portal'
    | '/api/public/diagnostic-email'
    | '/api/public/diagnostic-result'
    | '/api/public/diagnostic-token'
    | '/api/public/quiz-lead'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/diagnostic'
    | '/login'
    | '/portal'
    | '/pricing'
    | '/signup'
    | '/diagnostic/result'
    | '/portal/coach'
    | '/portal/setup'
    | '/portal/'
    | '/api/public/diagnostic-email'
    | '/api/public/diagnostic-result'
    | '/api/public/diagnostic-token'
    | '/api/public/quiz-lead'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DiagnosticRoute: typeof DiagnosticRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  ApiPublicDiagnosticEmailRoute: typeof ApiPublicDiagnosticEmailRoute
  ApiPublicDiagnosticResultRoute: typeof ApiPublicDiagnosticResultRoute
  ApiPublicDiagnosticTokenRoute: typeof ApiPublicDiagnosticTokenRoute
  ApiPublicQuizLeadRoute: typeof ApiPublicQuizLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic': {
      id: '/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof DiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/setup': {
      id: '/portal/setup'
      path: '/setup'
      fullPath: '/portal/setup'
      preLoaderRoute: typeof PortalSetupRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/coach': {
      id: '/portal/coach'
      path: '/coach'
      fullPath: '/portal/coach'
      preLoaderRoute: typeof PortalCoachRouteImport
      parentRoute: typeof PortalRoute
    }
    '/diagnostic/result': {
      id: '/diagnostic/result'
      path: '/result'
      fullPath: '/diagnostic/result'
      preLoaderRoute: typeof DiagnosticResultRouteImport
      parentRoute: typeof DiagnosticRoute
    }
    '/api/public/quiz-lead': {
      id: '/api/public/quiz-lead'
      path: '/api/public/quiz-lead'
      fullPath: '/api/public/quiz-lead'
      preLoaderRoute: typeof ApiPublicQuizLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/diagnostic-token': {
      id: '/api/public/diagnostic-token'
      path: '/api/public/diagnostic-token'
      fullPath: '/api/public/diagnostic-token'
      preLoaderRoute: typeof ApiPublicDiagnosticTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/diagnostic-result': {
      id: '/api/public/diagnostic-result'
      path: '/api/public/diagnostic-result'
      fullPath: '/api/public/diagnostic-result'
      preLoaderRoute: typeof ApiPublicDiagnosticResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/diagnostic-email': {
      id: '/api/public/diagnostic-email'
      path: '/api/public/diagnostic-email'
      fullPath: '/api/public/diagnostic-email'
      preLoaderRoute: typeof ApiPublicDiagnosticEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DiagnosticRouteChildren {
  DiagnosticResultRoute: typeof DiagnosticResultRoute
}

const DiagnosticRouteChildren: DiagnosticRouteChildren = {
  DiagnosticResultRoute: DiagnosticResultRoute,
}

const DiagnosticRouteWithChildren = DiagnosticRoute._addFileChildren(
  DiagnosticRouteChildren,
)

interface PortalRouteChildren {
  PortalCoachRoute: typeof PortalCoachRoute
  PortalSetupRoute: typeof PortalSetupRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalCoachRoute: PortalCoachRoute,
  PortalSetupRoute: PortalSetupRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DiagnosticRoute: DiagnosticRouteWithChildren,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  ApiPublicDiagnosticEmailRoute: ApiPublicDiagnosticEmailRoute,
  ApiPublicDiagnosticResultRoute: ApiPublicDiagnosticResultRoute,
  ApiPublicDiagnosticTokenRoute: ApiPublicDiagnosticTokenRoute,
  ApiPublicQuizLeadRoute: ApiPublicQuizLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
